[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "review-aspect-segmentation"
version = "0.1.0"
description = "Review aspect segmentation"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
include = ["segmentation*"]